#!/bin/bash

export OPENBUS_HOME=/openbus
export PATH="${OPENBUS_HOME}/bin:.:${PATH}"
export LD_LIBRARY_PATH="/usr/lib:/lib/i386-linux-gnu:${OPENBUS_HOME}/lib:${LD_LIBRARY_PATH}"
export LUA_PATH="${OPENBUS_HOME}/?.lua;${LUA_PATH}"

/openbus/bin/busservices -privatekey ${OPENBUS_HOME}/openbus.key -admin admin -validator validator


